# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: "dark" # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: "tomorrow-night-bright" # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : "https://deut-erium.github.io"
baseurl : "/"
title   : "deuterium's blog"
tagline : "Himanshu Sheoran's blog on tech, security, CTFs and cryptography"
description: > # this means to ignore newlines until "Language & timezone"
  Himanshu Sheoran is a nerd typically writing about cryptography, Capture
  The Flag i.e CTF events, hacking, cybersecurity, SAT SMT solvers and 
  computer science in general.
  


## => Language and Timezone
##############################
lang: en
timezone: Asia/Kolkata
future: true

## => Author and Social
##############################
author:
  type      : "person"
  name      : deuterium
  url       : https://deut-erium.github.io/
  avatar    : https://deut-erium.github.io/Circle-limit-IV.jpg
  bio       : Some words for the nerds
  email     : farziemailid69@gmail.com
  facebook  : #groups/csec.iitb # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : 0xdeuterium # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : himanshu-sheoran # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : deut-erium # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: deut-erium/WriteUps
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: false
mathjax_autoNumber: false

## Mermaid
mermaid: false

## Chart
chart: false


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: #false "disqus" # false (default), "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: https-deut-erium-github-io

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: "google" #default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: 416a5de1e771f1814 # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: "google" # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : "UA-161905683-1" # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : /:path

exclude:
  - LICENSE
  - CONTRIBUTING.md
  - directorize.py
  - jekyll-text-theme.gemspec

include:
  - README.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: false
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-postfiles
  - jekyll-seo-tag
